---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "TTCM Web Services"
subtitle: "Dashboard"
#logo: "logo.png"
icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: true 
columns: "3"

connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level. 

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'


# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
#message:
#  url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional message
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  #url: https://api.chucknorris.io/jokes/random
  #mapping:
  #  title: 'id'
  #  content: 'value'
  #refreshInterval: 10000
  #style: "is-warning"
  #title: "Optional message!"
  #icon: "fa fa-exclamation-triangle"
  #content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."


# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/mstemplinger"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "Blog"
    icon: "fas fa-file-alt"
    url: "https://tcude.net" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

services:
  - name: "Docker"
    icon: "fas fa-cloud"
    items:
      - name: "Portainer"
        logo: "assets/data/icons/portainer.png"
        subtitle: "Manage my dockers"
        tag: "app"
        url: "https://192.168.2.2:9000"
        target: "_blank" # optional html a tag target attribute
      - name: "NGinx"
        logo: "assets/data/icons/nginx.png"
        subtitle: "Manage my dockers"
        tag: "app"
        url: "https://192.168.2.2:81"
        target: "_blank" # optional html a tag target attribute        
      - name: "Git HowTo"
        logo: "assets/data/icons/git.png"
        subtitle: "Documentation Git"
        tag: "app"
        url: "https://www.atlassian.com/git/tutorials/syncing/git-pull"
        target: "_blank" # optional html a tag target attribute
      - name : "Homer HowTo"
        logo: "assets/data/icons/homer.png"
        tag: "app"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs"
        target: "_blank" # optional html a tag target attribute
      - name: "Font-Awesome"
        logo: "assets/data/icons/fontawesome.png"
        #subtitle: "SMART data at a glance"
        tag: "app"
        url: "https://fontawesome.com/v5/icons/cloud?f=classic&s=solid"
        target: "_blank" # optional html a tag target attribute
  - name: "My Containers"
    icon: "fas fa-wallet"
    items:
      - name: "Pi-hole"
        logo: "assets/data/icons/pihole.svg"
        subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        url: "http://192.168.2.225/admin"
        apikey: "23a93ad65b399a03f9b0212eda83aa515e72fdc5a0c9fc7a2becd6e31c76144e" # optional, needed if web interface is password protected
        type: "PiHole"
        tag: "PiHole"
        target: "_blank" # optional html a tag target attribute
      - name: "Vaultwarden"
        logo: "assets/data/icons/vaultwarden.png"
        subtitle: "Personal password manager "
        tag: "app"
        url: "https://vw.ttcm.duckdns.org/"
        target: "_blank" # optional html a tag target attribute
      - name: "Homebridge"
        logo: "assets/data/icons/homebridge.jpg"
        subtitle: "Homebridge allows you to integrate with smart home devices that do not natively support HomeKit. "
        tag: "app"
        url: "https://hb.ttcm.duckdns.org/"
        target: "_blank" # optional html a tag target attribute
      - name: "Wireguard"
        logo: "assets/data/icons/wireguard.png"
        subtitle: "My VPN Service"
        tag: "app"
        url: "https://wg.ttcm.duckdns.org/"
        target: "_blank" # optional html a tag target attribute
      - name: "Motioneye"
        logo: "assets/data/icons/motioneye.png"
        subtitle: "Camera Projekt"
        tag: "app"
        url: "https://me.ttcm.duckdns.org/"
        target: "_blank" # optional html a tag target attribute
      - name: "Homer"
        logo: "assets/data/icons/homer.png"
        subtitle: "This page"
        tag: "app"
        url: "https://hp.ttcm.duckdns.org/"
        target: "_blank" # optional html a tag target attribute
      - name: "Mosquitto"
        logo: "assets/data/icons/mosquitto.png"
        subtitle: "MQTT"
        tag: "app"
        #url: "http://192.168.2.2:8902/"       
  - name: "Media Server"
    icon: "fas fa-music"
    items:
      - name: "VU+ Duo4K"
        logo: "assets/data/icons/Duo4K.jpg"
        subtitle: "Premiere"
        tag: "app"
        url: "http://192.168.2.11"
        target: "_blank" # optional html a tag target attribute
      - name: "Plex"
        logo: "assets/data/icons/plex.png"
        subtitle: "Plex Media Server"
        tag: "app"
        url: "https://pi.ttcm.duckdns.org"
        target: "_blank" # optional html a tag target attribute
      - name: "Tautulli"
        logo: "assets/data/icons/tautulli.png"
        subtitle: "Plex Monitoring and Management"
        tag: "app"
        url: "https://tau.ttcm.duckdns.org"
        target: "_blank" # optional html a tag target attribute
#      - name: "Scrutiny"
#        logo: "assets/tools/sample.png"
#        subtitle: "SMART Info at a Glance"
#        tag: "app"
#        url: "10.10.2.101:8080/web/dashboard"
      - name: "SabNZBD"
        logo: "assets/data/icons/sabnzbd.png"
        subtitle: "SABNbzd NZBD downloader"
        tag: "app"
        url: "https://sab.ttcm.duckdns.org/sabnzbd/"
        target: "_blank" # optional html a tag target attribute
  - name: "Management"
    icon: "fas fa-user"
    items:
      - name: "Unifi"
        logo: "assets/data/icons/unifi2.png"
        subtitle: "Personal Unifi Network"
        tag: "app"
        url: "https://unifi.ttcm.duckdns.org"
        target: "_blank" # optional html a tag target attribute
      - name: "Fritz!Box"
        logo: "assets/data/icons/fritz.png"
        subtitle: "My Fritz!Box"
        tag: "app"
        url: "https://fritz.ttcm.duckdns.org"
        target: "_blank" # optional html a tag target attribute
      - name: "1home"
        logo: "assets/data/icons/1home-dark-logo.png"
        subtitle: "1home - Alexa"
        tag: "app"
        url: "https://my.1home.io"
        target: "_blank" # optional html a tag target attribute
      - name: "UptimeRobot"
        logo: "assets/data/icons/uptimerobot2.png"
        subtitle: "Monitor Service Uptime"
        tag: "app"
        url: "https://stats.uptimerobot.com/Hlq1oadhRW"
        target: "_blank" # optional html a tag target attribute
#      - name: "Cloudflare"
#        logo: "assets/tools/sample.png"
#        subtitle: "DNS and WAF"
#        tag: "app"
#        url: "https://dash.cloudflare.com/login"
#      - name: "Portainer - svr-docker-01"
#        logo: "assets/tools/sample.png"
#        subtitle: "Portainer instance residing on svr-docker-01"
#        tag: "app"
#        url: "http://10.10.80.192:9000/#!/home"
  - name: "Heimnetz"
    icon: "fas fa-house"
    items:
      - name: "Unifi-Manage"
        logo: "assets/data/icons/UniFi_Manage_192.1682.20_ubnt-300x178.png"
        subtitle: "gira"
        tag: "app"
        url: "http://192.168.2.20/"
        target: "_blank" # optional html a tag target attribute
      - name: "Gira TKS Türsystem"
        logo: "assets/data/icons/GiraTKSTuersystem-300x192.png"
        subtitle: "gira"
        tag: "app"
        url: "http://192.168.2.222:8080/"
        target: "_blank" # optional html a tag target attribute
      - name: "Heizung"
        logo: "assets/data/icons/Heizung_192.168.2.30_1..6-300x197.png"
        subtitle: ""
        tag: "app"
        url: "http://192.168.2.30/"
        target: "_blank" # optional html a tag target attribute
      - name: "NextServer"
        logo: "assets/data/icons/NextServer_192.168.2.210-xweb-300x151.png"
        subtitle: "KNX"
        tag: "app"
        url: "http://192.168.2.210/xweb"
        target: "_blank" # optional html a tag target attribute
      - name: "Zyxel-GS1920-24HP"
        logo: "assets/data/icons/Zyxel_switch_192.168.2.8-300x151.png"
        subtitle: "Switch(PoE)"
        tag: "app"
        url: "http://192.168.2.8/"
        target: "_blank" # optional html a tag target attribute
      - name: "Zyxel-GS1920-24"
        logo: "assets/data/icons/Zyxel_switch_192.168.2.8-300x151.png"
        subtitle: "Switch(non PoE)"
        tag: "app"
        url: "http://192.168.2.9/"
        target: "_blank" # optional html a tag target attribute
